const fs = require('fs');
const path = require('path');

const data = {
  version: "1.6",
  lastUpdated: "2025-12-07",
  fertilizers: [
    { id: "none", name: "No Fertilizer", growthBonus: 0, qualityBonus: 0, cost: 0 },
    { id: "speed-gro", name: "Speed-Gro", growthBonus: 0.10, qualityBonus: 0, cost: 100 },
    { id: "deluxe-speed-gro", name: "Deluxe Speed-Gro", growthBonus: 0.25, qualityBonus: 0, cost: 150 },
    { id: "hyper-speed-gro", name: "Hyper Speed-Gro", growthBonus: 0.33, qualityBonus: 0, cost: 70 },
    { id: "basic-fertilizer", name: "Basic Fertilizer", growthBonus: 0, qualityBonus: 1, cost: 100 },
    { id: "quality-fertilizer", name: "Quality Fertilizer", growthBonus: 0, qualityBonus: 2, cost: 150 },
    { id: "deluxe-fertilizer", name: "Deluxe Fertilizer", growthBonus: 0, qualityBonus: 3, cost: 70 }
  ],
  professions: [
    { id: "none", name: "No Profession", bonus: 0, appliesTo: [], description: "No profession bonus" },
    { id: "tiller", name: "Tiller", bonus: 0.10, appliesTo: ["Crops"], description: "+10% sell price for crops" },
    { id: "artisan", name: "Artisan", bonus: 0.40, appliesTo: ["Artisan Goods"], description: "+40% sell price for artisan goods" },
    { id: "agriculturist", name: "Agriculturist", growthBonus: 0.10, appliesTo: ["Crops"], description: "Crops grow 10% faster" },
    { id: "angler", name: "Angler", bonus: 0.25, appliesTo: ["Fish"], description: "+25% sell price for fish" },
    { id: "rancher", name: "Rancher", bonus: 0.20, appliesTo: ["Animal Products"], description: "+20% sell price for animal products" }
  ],
  seasons: ["Spring", "Summer", "Fall", "Winter", "Greenhouse"],
  items: [
    // Spring Crops
    { id: 1, name: "Parsnip", slug: "parsnip", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 35, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 4, regrows: false, description: "A spring tuber closely related to the carrot.", processing: { jarPrice: 120, jarProduct: "Pickles", kegPrice: 78, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 2, name: "Green Bean", slug: "green-bean", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 40, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: true, regrowTime: 3, description: "A popular garden plant with crunchy pods.", processing: { jarPrice: 130, jarProduct: "Pickles", kegPrice: 90, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 3, name: "Cauliflower", slug: "cauliflower", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 175, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 12, regrows: false, isGiantCrop: true, description: "Valuable, but slow-growing spring crop.", processing: { jarPrice: 400, jarProduct: "Pickles", kegPrice: 393, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 4, name: "Potato", slug: "potato", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 80, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 6, regrows: false, extraHarvestChance: 0.25, description: "A versatile tuber with excellent keeping qualities.", processing: { jarPrice: 210, jarProduct: "Pickles", kegPrice: 180, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 5, name: "Kale", slug: "kale", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 110, seedPrice: 70, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "Waxy leaves great for cooking. High in fiber.", processing: { jarPrice: 270, jarProduct: "Pickles", kegPrice: 247, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 6, name: "Garlic", slug: "garlic", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 60, seedPrice: 40, seedSource: "Pierre's Store (Year 2+)", growthTime: 4, regrows: false, description: "Adds wonderful flavor to dishes.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 7, name: "Rhubarb", slug: "rhubarb", category: "Crops", subcategory: "Fruit", season: ["Spring"], basePrice: 220, seedPrice: 100, seedSource: "Oasis", growthTime: 13, regrows: false, description: "Extremely tart stalks, great for desserts.", processing: { jarPrice: 490, jarProduct: "Jelly", kegPrice: 660, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 8, name: "Strawberry", slug: "strawberry", category: "Crops", subcategory: "Fruit", season: ["Spring"], basePrice: 120, seedPrice: 100, seedSource: "Egg Festival", growthTime: 8, regrows: true, regrowTime: 4, description: "A sweet spring fruit that keeps producing.", processing: { jarPrice: 290, jarProduct: "Jelly", kegPrice: 360, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 9, name: "Coffee Bean", slug: "coffee-bean", category: "Crops", subcategory: "Special", season: ["Spring", "Summer"], basePrice: 15, seedPrice: 2500, seedSource: "Traveling Cart", growthTime: 10, regrows: true, regrowTime: 2, harvestYield: 4, description: "Plant to grow coffee. Place 5 in a Keg for Coffee.", processing: { kegPrice: 150, kegProduct: "Coffee (x5)", kegTime: 2 } },
    { id: 10, name: "Blue Jazz", slug: "blue-jazz", category: "Crops", subcategory: "Flower", season: ["Spring"], basePrice: 50, seedPrice: 30, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "A delicate blue flower with juniper-like smell." },
    { id: 11, name: "Tulip", slug: "tulip", category: "Crops", subcategory: "Flower", season: ["Spring"], basePrice: 30, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "A colorful cup-shaped spring flower." },
    // Summer Crops
    { id: 12, name: "Melon", slug: "melon", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 250, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 12, regrows: false, isGiantCrop: true, description: "A refreshing summer fruit with sweet flavor.", processing: { jarPrice: 550, jarProduct: "Jelly", kegPrice: 750, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 13, name: "Tomato", slug: "tomato", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 60, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 11, regrows: true, regrowTime: 4, description: "Rich and tangy, with wide culinary uses.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 14, name: "Hot Pepper", slug: "hot-pepper", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 40, seedPrice: 40, seedSource: "Pierre's Store", growthTime: 5, regrows: true, regrowTime: 3, description: "Fiery with a hint of sweetness.", processing: { jarPrice: 130, jarProduct: "Jelly", kegPrice: 120, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 15, name: "Blueberry", slug: "blueberry", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 50, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 13, regrows: true, regrowTime: 4, harvestYield: 3, description: "Popular berry with many health benefits.", processing: { jarPrice: 150, jarProduct: "Jelly", kegPrice: 150, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 16, name: "Corn", slug: "corn", category: "Crops", subcategory: "Vegetable", season: ["Summer", "Fall"], basePrice: 50, seedPrice: 150, seedSource: "Pierre's Store", growthTime: 14, regrows: true, regrowTime: 4, description: "Popular grain, sweet fresh cobs are a summer treat.", processing: { jarPrice: 150, jarProduct: "Pickles", kegPrice: 100, kegProduct: "Oil", kegTime: 1, jarTime: 3 } },
    { id: 17, name: "Radish", slug: "radish", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 90, seedPrice: 40, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "A pungent root vegetable with red skin.", processing: { jarPrice: 230, jarProduct: "Pickles", kegPrice: 202, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 18, name: "Wheat", slug: "wheat", category: "Crops", subcategory: "Grain", season: ["Summer", "Fall"], basePrice: 25, seedPrice: 10, seedSource: "Pierre's Store", growthTime: 4, regrows: false, harvestTool: "Scythe", description: "Widely cultivated grain. Makes fine flour.", processing: { kegPrice: 200, kegProduct: "Beer", kegTime: 1.75 } },
    { id: 19, name: "Red Cabbage", slug: "red-cabbage", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 260, seedPrice: 100, seedSource: "Pierre's Store (Year 2+)", growthTime: 9, regrows: false, description: "Used in salads and coleslaws.", processing: { jarPrice: 570, jarProduct: "Pickles", kegPrice: 585, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 20, name: "Starfruit", slug: "starfruit", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 750, seedPrice: 400, seedSource: "Oasis", growthTime: 13, regrows: false, description: "Extremely juicy tropical fruit. Slightly sour with underlying sweetness.", processing: { jarPrice: 1550, jarProduct: "Jelly", kegPrice: 2250, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 21, name: "Hops", slug: "hops", category: "Crops", subcategory: "Special", season: ["Summer"], basePrice: 25, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 11, regrows: true, regrowTime: 1, isTrellis: true, description: "Bitter flower used to flavor beer.", processing: { kegPrice: 300, kegProduct: "Pale Ale", kegTime: 1.5 } },
    { id: 22, name: "Summer Spangle", slug: "summer-spangle", category: "Crops", subcategory: "Flower", season: ["Summer"], basePrice: 90, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 8, regrows: false, description: "A brilliant tropical flower." },
    { id: 23, name: "Poppy", slug: "poppy", category: "Crops", subcategory: "Flower", season: ["Summer"], basePrice: 140, seedPrice: 100, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "Has culinary and medicinal uses." },
    // Fall Crops
    { id: 24, name: "Pumpkin", slug: "pumpkin", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 320, seedPrice: 100, seedSource: "Pierre's Store", growthTime: 13, regrows: false, isGiantCrop: true, description: "A fall favorite, grown for sweet flesh and seeds.", processing: { jarPrice: 690, jarProduct: "Pickles", kegPrice: 720, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 25, name: "Eggplant", slug: "eggplant", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 60, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 5, regrows: true, regrowTime: 5, description: "A rich, purple vegetable with smooth skin.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 26, name: "Amaranth", slug: "amaranth", category: "Crops", subcategory: "Grain", season: ["Fall"], basePrice: 150, seedPrice: 70, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "Brilliant fuchsia crop, colorful addition to dishes.", processing: { jarPrice: 350, jarProduct: "Pickles", kegPrice: 337, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 27, name: "Grape", slug: "grape", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 80, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: true, regrowTime: 3, isTrellis: true, description: "A sweet cluster of fruit, perfect for wine.", processing: { jarPrice: 210, jarProduct: "Jelly", kegPrice: 240, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 28, name: "Yam", slug: "yam", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 160, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: false, description: "A starchy tuber with pinkish hue.", processing: { jarPrice: 370, jarProduct: "Pickles", kegPrice: 360, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 29, name: "Cranberries", slug: "cranberries", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 75, seedPrice: 240, seedSource: "Pierre's Store", growthTime: 7, regrows: true, regrowTime: 5, harvestYield: 2, description: "Tart red berries, traditional wintertime treat.", processing: { jarPrice: 200, jarProduct: "Jelly", kegPrice: 225, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 30, name: "Artichoke", slug: "artichoke", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 160, seedPrice: 30, seedSource: "Pierre's Store (Year 2+)", growthTime: 8, regrows: false, description: "Leafy green vegetable with nutty taste.", processing: { jarPrice: 370, jarProduct: "Pickles", kegPrice: 360, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 31, name: "Bok Choy", slug: "bok-choy", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 80, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 4, regrows: false, description: "Tender leaves, staple in stir fries.", processing: { jarPrice: 210, jarProduct: "Pickles", kegPrice: 180, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    { id: 32, name: "Fairy Rose", slug: "fairy-rose", category: "Crops", subcategory: "Flower", season: ["Fall"], basePrice: 290, seedPrice: 200, seedSource: "Pierre's Store", growthTime: 12, regrows: false, description: "A mystical flower said to bring good luck." },
    { id: 33, name: "Sunflower", slug: "sunflower", category: "Crops", subcategory: "Flower", season: ["Summer", "Fall"], basePrice: 80, seedPrice: 200, seedSource: "Pierre's Store", growthTime: 8, regrows: false, dropsSeed: true, description: "Sunny flower that can drop seeds when harvested." },
    // Special Crops
    { id: 34, name: "Sweet Gem Berry", slug: "sweet-gem-berry", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 3000, seedPrice: 1000, seedSource: "Traveling Cart", growthTime: 24, regrows: false, description: "The sweetest thing you've ever smelled." },
    { id: 35, name: "Ancient Fruit", slug: "ancient-fruit", category: "Crops", subcategory: "Fruit", season: ["Spring", "Summer", "Fall"], basePrice: 550, seedPrice: 0, seedSource: "Seed Maker", growthTime: 28, regrows: true, regrowTime: 7, description: "A rare prehistoric fruit.", processing: { jarPrice: 1150, jarProduct: "Jelly", kegPrice: 1650, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 36, name: "Pineapple", slug: "pineapple", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 300, seedPrice: 240, seedSource: "Island Trader", growthTime: 14, regrows: true, regrowTime: 7, description: "A tropical fruit with tangy flavor.", processing: { jarPrice: 650, jarProduct: "Jelly", kegPrice: 900, kegProduct: "Wine", kegTime: 7, jarTime: 3 } },
    { id: 37, name: "Taro Root", slug: "taro-root", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 100, seedPrice: 20, seedSource: "Island Trader", growthTime: 10, regrows: false, description: "Starchy root that grows in wet or dry soil.", processing: { jarPrice: 250, jarProduct: "Pickles", kegPrice: 225, kegProduct: "Juice", kegTime: 4, jarTime: 3 } },
    // Fish
    { id: 38, name: "Pufferfish", slug: "pufferfish", category: "Fish", subcategory: "Ocean", season: ["Summer"], basePrice: 200, location: "Ocean", time: "12pm - 4pm", weather: "Sunny", difficulty: 80, description: "Inflates when threatened." },
    { id: 39, name: "Sturgeon", slug: "sturgeon", category: "Fish", subcategory: "Lake", season: ["Summer", "Winter"], basePrice: 200, location: "Mountain Lake", time: "6am - 7pm", weather: "Any", difficulty: 78, description: "An ancient bottom-feeder. Roe becomes Caviar.", processing: { machine: "Fish Pond", product: "Sturgeon Roe → Caviar", price: 500 } },
    { id: 40, name: "Lava Eel", slug: "lava-eel", category: "Fish", subcategory: "Special", season: ["Spring", "Summer", "Fall", "Winter"], basePrice: 700, location: "Mines (Floor 100), Volcano", time: "Any", weather: "Any", difficulty: 90, description: "Can survive in molten lava." },
    { id: 41, name: "Legend", slug: "legend", category: "Fish", subcategory: "Legendary", season: ["Spring"], basePrice: 5000, location: "Mountain Lake", time: "6am - 8pm", weather: "Rainy", difficulty: 110, fishingLevel: 10, description: "The king of all fish!" },
    { id: 42, name: "Mutant Carp", slug: "mutant-carp", category: "Fish", subcategory: "Legendary", season: ["Spring", "Summer", "Fall", "Winter"], basePrice: 1000, location: "Sewers", time: "Any", weather: "Any", difficulty: 80, description: "Mutated by sewer conditions." },
    { id: 43, name: "Crimsonfish", slug: "crimsonfish", category: "Fish", subcategory: "Legendary", season: ["Summer"], basePrice: 1500, location: "Ocean (East Beach)", time: "6am - 8pm", weather: "Any", difficulty: 95, fishingLevel: 5, description: "Lives deep but comes to surface." },
    { id: 44, name: "Angler", slug: "angler-fish", category: "Fish", subcategory: "Legendary", season: ["Fall"], basePrice: 900, location: "Town River (North)", time: "6am - 8pm", weather: "Any", difficulty: 85, fishingLevel: 3, description: "Uses luminescent dangler to attract prey." },
    { id: 45, name: "Glacierfish", slug: "glacierfish", category: "Fish", subcategory: "Legendary", season: ["Winter"], basePrice: 1000, location: "Cindersap Forest (South)", time: "6am - 8pm", weather: "Any", difficulty: 100, fishingLevel: 6, description: "Builds nest under glaciers." },
    { id: 46, name: "Catfish", slug: "catfish", category: "Fish", subcategory: "River", season: ["Spring", "Summer", "Fall"], basePrice: 200, location: "River, Secret Woods", time: "6am - 12am", weather: "Rainy", difficulty: 75, description: "A whiskered bottom-feeder." },
    { id: 47, name: "Octopus", slug: "octopus", category: "Fish", subcategory: "Ocean", season: ["Summer"], basePrice: 150, location: "Ocean", time: "6am - 1pm", weather: "Any", difficulty: 95, description: "Mysterious and intelligent creature." },
    { id: 48, name: "Super Cucumber", slug: "super-cucumber", category: "Fish", subcategory: "Ocean", season: ["Summer", "Fall"], basePrice: 250, location: "Ocean", time: "6pm - 2am", weather: "Any", difficulty: 80, description: "A rare purple sea cucumber." },
    // Forage & Mushrooms
    { id: 49, name: "Truffle", slug: "truffle", category: "Animal Products", subcategory: "Pig", season: ["Spring", "Summer", "Fall"], basePrice: 625, source: "Pig (foraging)", description: "A gourmet mushroom with unique taste.", processing: { machine: "Oil Maker", product: "Truffle Oil", price: 1065, time: 6 } },
    { id: 50, name: "Morel", slug: "morel", category: "Forage", subcategory: "Mushroom", season: ["Spring"], basePrice: 150, location: "Secret Woods, Farm Cave", description: "Sought after for unique flavor." },
    { id: 51, name: "Chanterelle", slug: "chanterelle", category: "Forage", subcategory: "Mushroom", season: ["Fall"], basePrice: 160, location: "Secret Woods", description: "Delicious mushroom with fruity smell." },
    { id: 52, name: "Common Mushroom", slug: "common-mushroom", category: "Forage", subcategory: "Mushroom", season: ["Fall"], basePrice: 40, location: "Secret Woods, Farm Cave", description: "Slightly nutty with good texture." },
    { id: 53, name: "Purple Mushroom", slug: "purple-mushroom", category: "Forage", subcategory: "Mushroom", season: ["Spring", "Summer", "Fall", "Winter"], basePrice: 250, location: "Mines, Skull Cavern", description: "A rare mushroom from deep caves." },
    // Minerals
    { id: 54, name: "Diamond", slug: "diamond", category: "Minerals", subcategory: "Gem", basePrice: 750, source: "Mines (50+), Geodes, Panning", description: "A rare and valuable gem." },
    { id: 55, name: "Ruby", slug: "ruby", category: "Minerals", subcategory: "Gem", basePrice: 250, source: "Mines (80+), Geodes", description: "Precious stone with brilliant color." },
    { id: 56, name: "Emerald", slug: "emerald", category: "Minerals", subcategory: "Gem", basePrice: 250, source: "Mines (80+), Geodes", description: "Precious stone with brilliant green color." },
    { id: 57, name: "Jade", slug: "jade", category: "Minerals", subcategory: "Gem", basePrice: 200, source: "Mines (40+), Geodes", description: "Pale green ornamental stone." },
    { id: 58, name: "Prismatic Shard", slug: "prismatic-shard", category: "Minerals", subcategory: "Gem", basePrice: 2000, source: "Mystic Stone, Skull Cavern", description: "Very rare substance with unknown origins." },
    // Animal Products
    { id: 59, name: "Large Milk", slug: "large-milk", category: "Animal Products", subcategory: "Cow", basePrice: 190, source: "Cow (high friendship)", description: "A large jug of cow's milk.", processing: { machine: "Cheese Press", product: "Cheese (Gold)", price: 345, time: 3.3 } },
    { id: 60, name: "Large Egg", slug: "large-egg", category: "Animal Products", subcategory: "Chicken", basePrice: 95, source: "Chicken (high friendship)", description: "A large white egg.", processing: { machine: "Mayonnaise Machine", product: "Mayonnaise (Gold)", price: 285, time: 3 } },
    { id: 61, name: "Duck Egg", slug: "duck-egg", category: "Animal Products", subcategory: "Duck", basePrice: 95, source: "Duck", description: "A bit larger than a chicken egg.", processing: { machine: "Mayonnaise Machine", product: "Duck Mayonnaise", price: 375, time: 3 } },
    { id: 62, name: "Goat Milk", slug: "goat-milk", category: "Animal Products", subcategory: "Goat", basePrice: 225, source: "Goat", description: "The milk of a goat.", processing: { machine: "Cheese Press", product: "Goat Cheese", price: 400, time: 3.3 } },
    { id: 63, name: "Large Goat Milk", slug: "large-goat-milk", category: "Animal Products", subcategory: "Goat", basePrice: 345, source: "Goat (high friendship)", description: "A large jug of goat's milk.", processing: { machine: "Cheese Press", product: "Goat Cheese (Gold)", price: 600, time: 3.3 } },
    { id: 64, name: "Wool", slug: "wool", category: "Animal Products", subcategory: "Sheep/Rabbit", basePrice: 340, source: "Sheep, Rabbit", description: "Soft, fluffy wool.", processing: { machine: "Loom", product: "Cloth", price: 470, time: 4 } },
    { id: 65, name: "Rabbit's Foot", slug: "rabbits-foot", category: "Animal Products", subcategory: "Rabbit", basePrice: 565, source: "Rabbit (high friendship)", description: "Some say it's lucky." },
    { id: 66, name: "Dinosaur Egg", slug: "dinosaur-egg", category: "Animal Products", subcategory: "Dinosaur", basePrice: 350, source: "Dinosaur, Fishing, Artifact", description: "A giant prehistoric egg!", processing: { machine: "Mayonnaise Machine", product: "Dinosaur Mayonnaise", price: 800, time: 3 } },
    { id: 67, name: "Void Egg", slug: "void-egg", category: "Animal Products", subcategory: "Void Chicken", basePrice: 65, source: "Void Chicken", description: "A purplish egg from a strange chicken.", processing: { machine: "Mayonnaise Machine", product: "Void Mayonnaise", price: 275, time: 3 } },
    { id: 68, name: "Golden Egg", slug: "golden-egg", category: "Animal Products", subcategory: "Golden Chicken", basePrice: 500, source: "Golden Chicken", description: "A dazzling golden egg.", processing: { machine: "Mayonnaise Machine", product: "Gold Mayonnaise (x3)", price: 855, time: 3 } },
    { id: 69, name: "Ostrich Egg", slug: "ostrich-egg", category: "Animal Products", subcategory: "Ostrich", basePrice: 600, source: "Ostrich", description: "The world's largest egg!", processing: { machine: "Mayonnaise Machine", product: "Mayonnaise (x10)", price: 1000, time: 3 } },
    { id: 70, name: "Milk", slug: "milk", category: "Animal Products", subcategory: "Cow", basePrice: 125, source: "Cow", description: "A jug of cow's milk.", processing: { machine: "Cheese Press", product: "Cheese", price: 230, time: 3.3 } },
    { id: 71, name: "Egg", slug: "egg", category: "Animal Products", subcategory: "Chicken", basePrice: 50, source: "Chicken", description: "A regular white egg.", processing: { machine: "Mayonnaise Machine", product: "Mayonnaise", price: 190, time: 3 } }
  ]
};

const scriptDir = path.dirname(process.argv[1] || __filename);
const outputPath = path.join(scriptDir, '..', 'data', 'items.json');
console.log('Output path:', outputPath);
try {
  fs.writeFileSync(outputPath, JSON.stringify(data, null, 2), 'utf8');
  console.log(`Created items.json with ${data.items.length} items`);
  console.log(`Fertilizers: ${data.fertilizers.length}`);
  console.log(`Professions: ${data.professions.length}`);
} catch (err) {
  console.error('Error writing file:', err.message);
}
