const fs = require('fs');
const path = require('path');

const dataPath = path.join(__dirname, '..', 'data', 'items.json');
const data = require(dataPath);

// All items data
const items = [
  // Spring Crops
  { id: 1, name: "Parsnip", slug: "parsnip", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 35, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 4, regrows: false, description: "A spring tuber closely related to the carrot. It has an earthy taste and is full of nutrients.", processing: { jarPrice: 120, jarProduct: "Pickles", kegPrice: 78, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle"], giftLove: ["Pam"] },
  { id: 2, name: "Green Bean", slug: "green-bean", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 40, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: true, regrowTime: 3, description: "A popular garden plant. The young pods are crunchy and delicious.", processing: { jarPrice: 130, jarProduct: "Pickles", kegPrice: 90, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle"], giftLove: [] },
  { id: 3, name: "Cauliflower", slug: "cauliflower", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 175, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 12, regrows: false, isGiantCrop: true, description: "Valuable, but slow-growing. Despite its pale color, the florets are full of nutrients.", processing: { jarPrice: 400, jarProduct: "Pickles", kegPrice: 393, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle", "Quality Crops Bundle"], giftLove: ["Maru"] },
  { id: 4, name: "Potato", slug: "potato", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 80, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 6, regrows: false, extraHarvestChance: 0.25, description: "A brown tuber with excellent keeping qualities. Very versatile in cooking.", processing: { jarPrice: 210, jarProduct: "Pickles", kegPrice: 180, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle"], giftLove: [] },
  { id: 5, name: "Kale", slug: "kale", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 110, seedPrice: 70, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "The waxy leaves are great for cooking. High in fiber and vitamins.", processing: { jarPrice: 270, jarProduct: "Pickles", kegPrice: 247, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle"], giftLove: [] },
  { id: 6, name: "Garlic", slug: "garlic", category: "Crops", subcategory: "Vegetable", season: ["Spring"], basePrice: 60, seedPrice: 40, seedSource: "Pierre's Store (Year 2+)", growthTime: 4, regrows: false, description: "Adds a wonderful aroma to any dish. High-quality garlic can be quite valuable.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Spring Crops Bundle"], giftLove: [] },
  { id: 7, name: "Rhubarb", slug: "rhubarb", category: "Crops", subcategory: "Fruit", season: ["Spring"], basePrice: 220, seedPrice: 100, seedSource: "Oasis", growthTime: 13, regrows: false, description: "The stalks are sour, but make a great dessert when sweetened.", processing: { jarPrice: 490, jarProduct: "Jelly", kegPrice: 660, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: [], giftLove: [] },
  { id: 8, name: "Strawberry", slug: "strawberry", category: "Crops", subcategory: "Fruit", season: ["Spring"], basePrice: 120, seedPrice: 100, seedSource: "Egg Festival", growthTime: 8, regrows: true, regrowTime: 4, description: "A sweet, popular berry with a red color and seedy skin.", processing: { jarPrice: 290, jarProduct: "Jelly", kegPrice: 360, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: [], giftLove: ["Demetrius", "Maru"] },
  { id: 9, name: "Coffee Bean", slug: "coffee-bean", category: "Crops", subcategory: "Other", season: ["Spring", "Summer"], basePrice: 15, seedPrice: 2500, seedSource: "Traveling Cart", growthTime: 10, regrows: true, regrowTime: 2, harvestQuantity: 4, description: "Can be brewed into coffee. Plant in spring or summer.", processing: { machine: "Keg", product: "Coffee", price: 150, time: 2, inputQuantity: 5 }, usedIn: [], giftLove: [] },
  { id: 10, name: "Blue Jazz", slug: "blue-jazz", category: "Crops", subcategory: "Flower", season: ["Spring"], basePrice: 50, seedPrice: 30, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "The blue petals produce a popular flower. Nice as a decoration.", processing: null, usedIn: ["Spring Crops Bundle"], giftLove: [] },
  { id: 11, name: "Tulip", slug: "tulip", category: "Crops", subcategory: "Flower", season: ["Spring"], basePrice: 30, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "The most popular spring flower. Has a very faint sweet smell.", processing: null, usedIn: [], giftLove: ["Evelyn"] },
  
  // Summer Crops
  { id: 12, name: "Melon", slug: "melon", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 250, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 12, regrows: false, isGiantCrop: true, description: "A big, juicy fruit with a refreshing taste. Perfect for a hot summer day.", processing: { jarPrice: 550, jarProduct: "Jelly", kegPrice: 750, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Summer Crops Bundle", "Quality Crops Bundle"], giftLove: [] },
  { id: 13, name: "Tomato", slug: "tomato", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 60, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 11, regrows: true, regrowTime: 4, description: "A savory, juicy vegetable with a slightly bitter taste.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Summer Crops Bundle"], giftLove: [] },
  { id: 14, name: "Hot Pepper", slug: "hot-pepper", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 40, seedPrice: 40, seedSource: "Pierre's Store", growthTime: 5, regrows: true, regrowTime: 3, description: "A fiery little pepper with a strong spicy flavor.", processing: { jarPrice: 130, jarProduct: "Jelly", kegPrice: 120, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Summer Crops Bundle"], giftLove: ["Lewis", "Shane"] },
  { id: 15, name: "Blueberry", slug: "blueberry", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 50, seedPrice: 80, seedSource: "Pierre's Store", growthTime: 13, regrows: true, regrowTime: 4, harvestQuantity: 3, description: "A sweet berry with a tart flavor. The staining juice is used for dye.", processing: { jarPrice: 150, jarProduct: "Jelly", kegPrice: 150, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Summer Crops Bundle"], giftLove: [] },
  { id: 16, name: "Corn", slug: "corn", category: "Crops", subcategory: "Vegetable", season: ["Summer", "Fall"], basePrice: 50, seedPrice: 150, seedSource: "Pierre's Store", growthTime: 14, regrows: true, regrowTime: 4, description: "One of the world's most popular grains. Naturally sweet but bland when over-cooked.", processing: { jarPrice: 150, jarProduct: "Pickles", kegPrice: 112, kegProduct: "Juice", kegTime: 4, jarTime: 3, oilMakerPrice: 100 }, usedIn: ["Summer Crops Bundle", "Fall Crops Bundle"], giftLove: [] },
  { id: 17, name: "Radish", slug: "radish", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 90, seedPrice: 40, seedSource: "Pierre's Store", growthTime: 6, regrows: false, description: "A crunchy white root with a peppery zip to it.", processing: { jarPrice: 230, jarProduct: "Pickles", kegPrice: 202, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Summer Crops Bundle"], giftLove: [] },
  { id: 18, name: "Wheat", slug: "wheat", category: "Crops", subcategory: "Other", season: ["Summer", "Fall"], basePrice: 25, seedPrice: 10, seedSource: "Pierre's Store", growthTime: 4, regrows: false, harvestTool: "Scythe", description: "A cereal grain used for flour or brewing.", processing: { kegPrice: 200, kegProduct: "Beer", kegTime: 1 }, usedIn: ["Fodder Bundle"], giftLove: [] },
  { id: 19, name: "Red Cabbage", slug: "red-cabbage", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 260, seedPrice: 100, seedSource: "Pierre's Store (Year 2+)", growthTime: 9, regrows: false, description: "A colorful variety of cabbage often used in salads.", processing: { jarPrice: 570, jarProduct: "Pickles", kegPrice: 585, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Dye Bundle"], giftLove: ["Demetrius"] },
  { id: 20, name: "Starfruit", slug: "starfruit", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 750, seedPrice: 400, seedSource: "Oasis", growthTime: 13, regrows: false, description: "An extremely juicy fruit that grows in hot, humid weather. The most profitable fruit crop.", processing: { jarPrice: 1550, jarProduct: "Jelly", kegPrice: 2250, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Dye Bundle"], giftLove: [] },
  { id: 21, name: "Hops", slug: "hops", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 25, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 11, regrows: true, regrowTime: 1, description: "A very bitter plant mainly used for brewing beer. Extremely profitable with daily harvests.", processing: { kegPrice: 300, kegProduct: "Pale Ale", kegTime: 2 }, usedIn: ["Summer Crops Bundle"], giftLove: [] },
  { id: 22, name: "Summer Spangle", slug: "summer-spangle", category: "Crops", subcategory: "Flower", season: ["Summer"], basePrice: 90, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 8, regrows: false, description: "A cheerful, orange-red flower that thrives in warm weather.", processing: null, usedIn: [], giftLove: [] },
  { id: 23, name: "Poppy", slug: "poppy", category: "Crops", subcategory: "Flower", season: ["Summer"], basePrice: 140, seedPrice: 100, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "A bright, cheerful flower that has a very pleasant scent.", processing: null, usedIn: [], giftLove: ["Penny"] },
  
  // Fall Crops
  { id: 24, name: "Pumpkin", slug: "pumpkin", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 320, seedPrice: 100, seedSource: "Pierre's Store", growthTime: 13, regrows: false, isGiantCrop: true, description: "A fall favorite, grown for its crunchy seeds and delicately flavored flesh.", processing: { jarPrice: 690, jarProduct: "Pickles", kegPrice: 720, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Fall Crops Bundle", "Quality Crops Bundle"], giftLove: ["Abigail", "Krobus", "Willy"] },
  { id: 25, name: "Eggplant", slug: "eggplant", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 60, seedPrice: 20, seedSource: "Pierre's Store", growthTime: 5, regrows: true, regrowTime: 5, description: "A rich, purple vegetable with a soft, spongy texture.", processing: { jarPrice: 170, jarProduct: "Pickles", kegPrice: 135, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Fall Crops Bundle"], giftLove: [] },
  { id: 26, name: "Amaranth", slug: "amaranth", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 150, seedPrice: 70, seedSource: "Pierre's Store", growthTime: 7, regrows: false, description: "An ancient grain that was a staple food for many cultures. The leaves are edible too.", processing: { jarPrice: 350, jarProduct: "Pickles", kegPrice: 337, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Fall Crops Bundle"], giftLove: [] },
  { id: 27, name: "Grape", slug: "grape", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 80, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: true, regrowTime: 3, description: "A ripe cluster of grapes. Very sweet and juicy.", processing: { jarPrice: 210, jarProduct: "Jelly", kegPrice: 240, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Fall Crops Bundle"], giftLove: ["Vincent"] },
  { id: 28, name: "Yam", slug: "yam", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 160, seedPrice: 60, seedSource: "Pierre's Store", growthTime: 10, regrows: false, description: "A starchy tuber with a creamy, orange flesh.", processing: { jarPrice: 370, jarProduct: "Pickles", kegPrice: 360, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: ["Fall Crops Bundle"], giftLove: [] },
  { id: 29, name: "Cranberries", slug: "cranberries", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 75, seedPrice: 240, seedSource: "Pierre's Store", growthTime: 7, regrows: true, regrowTime: 5, harvestQuantity: 2, description: "Small, tart berries often used in cooking or juicing. Produces multiple harvests.", processing: { jarPrice: 200, jarProduct: "Jelly", kegPrice: 225, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Fall Crops Bundle"], giftLove: [] },
  { id: 30, name: "Artichoke", slug: "artichoke", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 160, seedPrice: 30, seedSource: "Pierre's Store (Year 2+)", growthTime: 8, regrows: false, description: "A bud of a large, flowering plant. The petals are edible.", processing: { jarPrice: 370, jarProduct: "Pickles", kegPrice: 360, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: [], giftLove: [] },
  { id: 31, name: "Bok Choy", slug: "bok-choy", category: "Crops", subcategory: "Vegetable", season: ["Fall"], basePrice: 80, seedPrice: 50, seedSource: "Pierre's Store", growthTime: 4, regrows: false, description: "A leafy vegetable often used in stir-fries. Very healthy.", processing: { jarPrice: 210, jarProduct: "Pickles", kegPrice: 180, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: [], giftLove: [] },
  { id: 32, name: "Fairy Rose", slug: "fairy-rose", category: "Crops", subcategory: "Flower", season: ["Fall"], basePrice: 290, seedPrice: 200, seedSource: "Pierre's Store", growthTime: 12, regrows: false, honeyPrice: 680, description: "An extremely rare, mystical flower. Produces the most valuable honey.", processing: null, usedIn: [], giftLove: ["Jas", "Evelyn"] },
  { id: 33, name: "Sunflower", slug: "sunflower", category: "Crops", subcategory: "Flower", season: ["Summer", "Fall"], basePrice: 80, seedPrice: 200, seedSource: "Pierre's Store", growthTime: 8, regrows: false, description: "A large, cheerful flower. Can also produce seeds and oil.", processing: { oilMakerPrice: 100 }, usedIn: ["Dye Bundle"], giftLove: ["Haley"] },
  { id: 34, name: "Sweet Gem Berry", slug: "sweet-gem-berry", category: "Crops", subcategory: "Fruit", season: ["Fall"], basePrice: 3000, seedPrice: 1000, seedSource: "Traveling Cart (Rare Seed)", growthTime: 24, regrows: false, description: "The most valuable crop in the game. Takes a full season to grow.", processing: null, usedIn: [], giftLove: [] },
  { id: 35, name: "Ancient Fruit", slug: "ancient-fruit", category: "Crops", subcategory: "Fruit", season: ["Spring", "Summer", "Fall"], basePrice: 550, seedPrice: 0, seedSource: "Seed Maker", growthTime: 28, regrows: true, regrowTime: 7, description: "A mysterious fruit from an ancient era. Best grown in greenhouse for year-round profit.", processing: { jarPrice: 1150, jarProduct: "Jelly", kegPrice: 1650, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: ["Rare Crops Bundle", "Missing Bundle"], giftLove: [] },
  { id: 36, name: "Pineapple", slug: "pineapple", category: "Crops", subcategory: "Fruit", season: ["Summer"], basePrice: 300, seedPrice: 240, seedSource: "Ginger Island", growthTime: 14, regrows: true, regrowTime: 7, description: "A tropical fruit with a sweet, tangy flavor. Only grows on Ginger Island or greenhouse.", processing: { jarPrice: 650, jarProduct: "Jelly", kegPrice: 900, kegProduct: "Wine", kegTime: 7, jarTime: 3 }, usedIn: [], giftLove: [] },
  { id: 37, name: "Taro Root", slug: "taro-root", category: "Crops", subcategory: "Vegetable", season: ["Summer"], basePrice: 100, seedPrice: 40, seedSource: "Ginger Island", growthTime: 10, regrows: false, description: "A starchy root vegetable that grows well in tropical conditions.", processing: { jarPrice: 250, jarProduct: "Pickles", kegPrice: 225, kegProduct: "Juice", kegTime: 4, jarTime: 3 }, usedIn: [], giftLove: [] },
  
  // Fish
  { id: 40, name: "Pufferfish", slug: "pufferfish", category: "Fish", subcategory: "Ocean", season: ["Summer"], basePrice: 200, time: "12pm - 4pm", weather: "Sunny", location: "Ocean", difficulty: 80, description: "Inflates when threatened. Can poison a sashimi chef if not prepared correctly.", processing: null, usedIn: ["Specialty Fish Bundle"], giftLove: ["Abigail"] },
  { id: 41, name: "Sturgeon", slug: "sturgeon", category: "Fish", subcategory: "Lake", season: ["Summer", "Winter"], basePrice: 200, time: "6am - 7pm", weather: "Any", location: "Mountain Lake", difficulty: 78, description: "An ancient armored fish. Produces high-quality roe for caviar.", processing: { machine: "Fish Pond", product: "Sturgeon Roe → Caviar", price: 500 }, usedIn: ["Lake Fish Bundle"], giftLove: [] },
  { id: 42, name: "Lava Eel", slug: "lava-eel", category: "Fish", subcategory: "Mine", season: ["All"], basePrice: 700, time: "Any", weather: "Any", location: "Mines Floor 100", difficulty: 90, description: "It can somehow survive in pools of molten lava. Very rare and valuable.", processing: { machine: "Fish Pond", product: "Roe", price: 1064 }, usedIn: [], giftLove: [] },
  { id: 43, name: "Legend", slug: "legend", category: "Fish", subcategory: "Legendary", season: ["Spring"], basePrice: 5000, time: "6am - 8pm", weather: "Rainy", location: "Mountain Lake", difficulty: 110, description: "The king of all fish! They say he's uncatchable. Requires Fishing level 10.", processing: null, usedIn: [], giftLove: [] },
  { id: 44, name: "Crimsonfish", slug: "crimsonfish", category: "Fish", subcategory: "Legendary", season: ["Summer"], basePrice: 1500, time: "Any", weather: "Any", location: "East Pier", difficulty: 95, description: "Lives deep in the ocean but likes to come near the shore to bathe in warm sunlight.", processing: null, usedIn: [], giftLove: [] },
  { id: 45, name: "Angler", slug: "angler-fish", category: "Fish", subcategory: "Legendary", season: ["Fall"], basePrice: 900, time: "Any", weather: "Any", location: "North of JojaMart", difficulty: 85, description: "Uses a bioluminescent dangler to attract prey.", processing: null, usedIn: [], giftLove: [] },
  { id: 46, name: "Glacierfish", slug: "glacierfish", category: "Fish", subcategory: "Legendary", season: ["Winter"], basePrice: 1000, time: "Any", weather: "Any", location: "Arrowhead Island", difficulty: 100, description: "A fish that thrives in extremely cold conditions.", processing: null, usedIn: [], giftLove: [] },
  { id: 47, name: "Mutant Carp", slug: "mutant-carp", category: "Fish", subcategory: "Legendary", season: ["All"], basePrice: 1000, time: "Any", weather: "Any", location: "Sewers", difficulty: 80, description: "Clearly mutation has occurred. The source is unknown.", processing: null, usedIn: [], giftLove: [] },
  { id: 48, name: "Catfish", slug: "catfish", category: "Fish", subcategory: "River", season: ["Spring", "Fall", "Summer"], basePrice: 200, time: "6am - 12am", weather: "Rainy", location: "River", difficulty: 75, description: "A lurking hunter. Uses long whisker-like feelers to detect nearby prey.", processing: null, usedIn: ["River Fish Bundle"], giftLove: [] },
  { id: 49, name: "Octopus", slug: "octopus", category: "Fish", subcategory: "Ocean", season: ["Summer"], basePrice: 150, time: "6am - 1pm", weather: "Any", location: "Ocean", difficulty: 95, description: "A soft-bodied cephalopod known for its intelligence.", processing: null, usedIn: [], giftLove: [] },
  { id: 50, name: "Super Cucumber", slug: "super-cucumber", category: "Fish", subcategory: "Ocean", season: ["Summer", "Fall"], basePrice: 250, time: "6pm - 2am", weather: "Any", location: "Ocean", difficulty: 80, description: "It's about 10x larger than a normal sea cucumber.", processing: null, usedIn: [], giftLove: [] },
  { id: 51, name: "Largemouth Bass", slug: "largemouth-bass", category: "Fish", subcategory: "Lake", season: ["All"], basePrice: 100, time: "6am - 7pm", weather: "Any", location: "Mountain Lake", difficulty: 50, description: "A popular game fish known for its large mouth.", processing: null, usedIn: ["Lake Fish Bundle"], giftLove: [] },
  { id: 52, name: "Salmon", slug: "salmon", category: "Fish", subcategory: "River", season: ["Fall"], basePrice: 75, time: "6am - 7pm", weather: "Any", location: "River", difficulty: 50, description: "Swims upstream to lay eggs during the fall.", processing: null, usedIn: ["River Fish Bundle"], giftLove: [] },
  { id: 53, name: "Carp", slug: "carp", category: "Fish", subcategory: "Lake", season: ["All"], basePrice: 30, time: "Any", weather: "Any", location: "Mountain Lake", difficulty: 15, description: "A common fish found in ponds and lakes.", processing: null, usedIn: ["Lake Fish Bundle"], giftLove: [] },
  
  // Forage
  { id: 60, name: "Truffle", slug: "truffle", category: "Forage", subcategory: "Animal Product", season: ["Spring", "Summer", "Fall"], basePrice: 625, description: "A gourmet type of mushroom with a unique, earthy taste. Found by pigs.", processing: { machine: "Oil Maker", product: "Truffle Oil", price: 1065, time: 6 }, usedIn: ["Chef's Bundle"], giftLove: ["Leah"] },
  { id: 61, name: "Common Mushroom", slug: "common-mushroom", category: "Forage", subcategory: "Forest", season: ["Spring", "Fall"], basePrice: 40, description: "Slightly nutty, with good texture.", processing: null, usedIn: ["Fall Foraging Bundle"], giftLove: [] },
  { id: 62, name: "Morel", slug: "morel", category: "Forage", subcategory: "Forest", season: ["Spring"], basePrice: 150, description: "A special mushroom with a unique honeycomb pattern. Highly prized by chefs.", processing: null, usedIn: ["Spring Foraging Bundle"], giftLove: [] },
  { id: 63, name: "Chanterelle", slug: "chanterelle", category: "Forage", subcategory: "Forest", season: ["Fall"], basePrice: 160, description: "A golden colored mushroom with a fruity smell.", processing: null, usedIn: ["Fall Foraging Bundle"], giftLove: [] },
  
  // Minerals
  { id: 70, name: "Diamond", slug: "diamond", category: "Minerals", subcategory: "Gem", season: ["All"], basePrice: 750, description: "A rare and valuable gem.", processing: null, usedIn: [], giftLove: ["Evelyn", "Gus", "Jodi", "Krobus", "Marnie", "Maru", "Penny", "Willy"] },
  { id: 71, name: "Ruby", slug: "ruby", category: "Minerals", subcategory: "Gem", season: ["All"], basePrice: 250, description: "A precious gem that is prized for its beautiful red color.", processing: null, usedIn: [], giftLove: [] },
  { id: 72, name: "Emerald", slug: "emerald", category: "Minerals", subcategory: "Gem", season: ["All"], basePrice: 250, description: "A precious gem that is prized for its green color.", processing: null, usedIn: [], giftLove: ["Penny"] },
  { id: 73, name: "Prismatic Shard", slug: "prismatic-shard", category: "Minerals", subcategory: "Gem", season: ["All"], basePrice: 2000, description: "A very rare and powerful substance with unknown origins.", processing: null, usedIn: ["Missing Bundle"], giftLove: [] },
  
  // Animal Products
  { id: 80, name: "Large Milk", slug: "large-milk", category: "Animal Products", subcategory: "Cow", season: ["All"], basePrice: 190, description: "A large jug of fresh cow's milk.", processing: { machine: "Cheese Press", product: "Cheese", price: 240, time: 3.3 }, usedIn: ["Animal Bundle"], giftLove: [] },
  { id: 81, name: "Large Egg", slug: "large-egg", category: "Animal Products", subcategory: "Chicken", season: ["All"], basePrice: 95, description: "A large white chicken egg.", processing: { machine: "Mayonnaise Machine", product: "Mayonnaise", price: 190, time: 3 }, usedIn: ["Animal Bundle"], giftLove: [] },
  { id: 82, name: "Duck Egg", slug: "duck-egg", category: "Animal Products", subcategory: "Duck", season: ["All"], basePrice: 95, description: "It's quite large and spotted with blue.", processing: { machine: "Mayonnaise Machine", product: "Duck Mayonnaise", price: 375, time: 3 }, usedIn: ["Animal Bundle"], giftLove: [] },
  { id: 83, name: "Goat Milk", slug: "goat-milk", category: "Animal Products", subcategory: "Goat", season: ["All"], basePrice: 225, description: "The thick, creamy milk of a goat.", processing: { machine: "Cheese Press", product: "Goat Cheese", price: 400, time: 3.3 }, usedIn: ["Animal Bundle"], giftLove: [] },
  { id: 84, name: "Wool", slug: "wool", category: "Animal Products", subcategory: "Sheep/Rabbit", season: ["All"], basePrice: 340, description: "Soft, fluffy wool from sheep or rabbit.", processing: { machine: "Loom", product: "Cloth", price: 470, time: 4 }, usedIn: ["Artisan Bundle"], giftLove: [] },
  { id: 85, name: "Rabbit's Foot", slug: "rabbits-foot", category: "Animal Products", subcategory: "Rabbit", season: ["All"], basePrice: 565, description: "Thought to bring good luck. Rare drop from happy rabbits.", processing: null, usedIn: ["Enchanter's Bundle"], giftLove: ["Penny"] },
  { id: 86, name: "Dinosaur Egg", slug: "dinosaur-egg", category: "Animal Products", subcategory: "Dinosaur", season: ["All"], basePrice: 350, description: "A giant dino egg... The dinosaur must've been huge!", processing: { machine: "Mayonnaise Machine", product: "Dinosaur Mayonnaise", price: 800, time: 3 }, usedIn: [], giftLove: [] },
  { id: 87, name: "Void Egg", slug: "void-egg", category: "Animal Products", subcategory: "Void Chicken", season: ["All"], basePrice: 65, description: "A strange egg from another realm.", processing: { machine: "Mayonnaise Machine", product: "Void Mayonnaise", price: 275, time: 3 }, usedIn: [], giftLove: ["Krobus", "Sebastian"] }
];

data.items = items;

fs.writeFileSync(dataPath, JSON.stringify(data, null, 2), 'utf8');
console.log(`Successfully wrote ${items.length} items to items.json`);
